### ISSUE TITLE
When the Ajaxrequest in script.js replaces an HTML line, the {% static } Django template does not seem to be interpreted

### ISSUE THREAD

**Issue by sguillot** [sguillot/CompARE#37]
After filtering sources, the display table is updated, but the AjaxRequest does not seem to interpret properly the {% static} Django template that links to images in the static folder, or to data file.

In the updated table HTML page, the links look like: 
```
<img src="{% static 'compare/download.svg' %}" alt="icon download" width="30em">
```
instead of 
```
<img src="/static/compare/download.svg" alt="icon download" width="30em">
```

**Comment by sguillot** [comment]
Issue appears as of 85c746f00f28c112cb3753202870e61704dc9d8e

**Comment by sguillot** [comment]
The same problem appears for the `href` to the file to download. Somewhere in the `script.js` file 
I had commented the `href` from the `download.innerHTML`, but it should be added back to the `basaStaticURL`.
```
        download.innerHTML = "<img src='" + baseStaticURL + "compare/download.svg' alt='icon download' width='30em' />"

        // Commenting the download for now since even the image doesn't work!
        // download.innerHTML = "<a href="+ d.filpath + " download> <img src='{% static \"compare/download.svg\" %}' alt='icon download' width='30em' /></a>"
        // download.innerHTML = "<a href='{% static \"data/"+ d.filename + "\" %}' download='{% static \"data/"+ d.filename + "\" %}'><img src='{% static \"compare/download.svg\" %}' alt='icon download' width='30em' /></a>"
```
(I don't know which of the two commented lines will work)

**Comment by Mazlai** [comment]
The bottom line is the most likely to work, but I forgot to adapt this part of the code because I was just displaying the image... 


All I had to do was replace each Django tag occurrence with the `baseStaticURL` variable like this :

```js
download.innerHTML = "<a href='" + baseStaticURL + "data/" + d.filename + "' download='" + baseStaticURL + "data/" + d.filename + "'>" + "<img src='" + baseStaticURL + "compare/download.svg' alt='icon download' width='30em' />" + "</a>";
```

The commit is done !
